[package]
name = "rustbase"
version = "0.1.0"
authors = ["jenra <24357776+jenra-uwu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rustbase"
path = "src/lib.rs"

[dependencies]
